# Generated by Django 4.0.6 on 2022-08-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=42)),
                ('amount', models.IntegerField(default=0)),
                ('payment', models.BooleanField(default=False)),
                ('function', models.CharField(blank=True, max_length=800)),
                ('params', models.JSONField(blank=True, null=True)),
                ('chain', models.IntegerField(default=1)),
            ],
        ),
    ]
